namespace Feliciabot.net._6._0.models
{
    public static class Responses
    {
        public static readonly string[][] RollResponses =
        [
            [
                "As I see it, yes",
                "It is certain!",
                "Most likely!",
                "Outlook good!",
                "Signs point to yes",
                "Without a doubt",
                "Yes",
                "Yes - definitely",
            ],
            [
                "Don't count on it",
                "My reply is no",
                "My sources say no",
                "Outlook not so good",
                "Very doubtful",
            ],
            [
                "Reply hazy, try again",
                "Ask again later",
                "Better not tell you now",
                "Cannot predict now",
                "Concentrate and ask again",
            ],
        ];

        public static readonly string[] TeaResponses =
        [
            "Honey",
            "Green",
            "Oolong",
            "White",
            "Yellow",
            "Mulberry",
            "Herbal",
            "Chai",
            "Ceylon",
            "Mint ginger lemon",
            "Chamomile with lemongrass",
            "Spearmint",
            "Peppermint",
            "Chamomile",
            "Mulberry",
            "Hibiscus",
            "Jasmine",
            "Rooibos",
            "Milk",
            "Frozen Milk",
        ];

        public static readonly string[] GreetingResponses =
        [
            "Nice to see you!",
            "Can I get you something?",
            "I'll do my best to be of service!",
            "Whoa! Wh-whoa! Whoa!",
            "We've got trouble!",
            "Didn't expect that, did ya?",
            "All right!",
            "Hiho!",
            "Greetings, comrade!",
            "Welcome to maid hell, enjoy your stay!",
            "OwO!",
            "Here goes nothing!",
            "Yay!",
        ];

        public static readonly string[] FeliciaQuotes =
        [
            "My name is Felicia. I'm one of the very best maids from the Kingdom of—! Whoa! Sorry. Dropped my tea tray.",
            "The outfits for the Order of Heroes are great. I love the fluttery white capes! Wish I could try one on.",
            "I do my best to carry a tea tray with poise and elegance. But, uh... I'll drop it every time!",
            "I'm not the best at making tea, but I'll make you some if you want. I... I hope you like it bitter!",
            "Did you know that I'm from the Ice Tribe of my world? Now you do!",
            "Oh no! I broke another plate!",
            "I'll be sure to wake everyone up, first thing in the morning. You can count on it.",
            "I think I deserve a raise!",
            "Whoa, sorry... Flubbed that.",
            "Didn't expect that, did ya?",
            "You're just a stain!",
            "No mercy! Not from me!",
            "Oh, I wish people would clean up after themselves!",
            "Sorry, I can't really chat right now. Laundry and chores are backing up!",
            "I'm actually more confident on the battlefield than I am in the kitchen.",
            "Thanks for always being so nice to me... You've never made me feel like a servant.",
            "I know we're friends, but I'm still happy to work for you. Call me anytime!",
            "We've got trouble!",
            "Here goes nothing!",
            "I'm gonna break you!",
            "I won't mess this up!",
            "All taken care of!",
            "This looks like a job for Super Felicia!",
            "Why yes, I am a hardcore otaku.",
            "Hi!",
            "Oof.",
            "Yeet.",
            "Big MEATY claws!",
            "My body is ready.",
            "Make sure to pick up Fire Emblem Fates at your nearest Nintendo retailer.",
            "War. War never changes.",
            "wat",
            "ICE to meet you.",
            "Aiba sus.",
            "Death.",
            "Hello! You know who asked me to stop by and say hello? It was Corrin! And now... I've said it twice!",
            "*nervous laugh*",
            "Whoa.",
            "Ganbare beam!",
            "Have you played Trails in the Sky?",
            "Even though Corrin is my master I actually main Ice Climbers in Smash Ultimate.",
            "I miss the Ice Tribe...Maybe I'm just looking through froze-colored glasses.",
            "I was trying to tell you that I was choking on snow, but the snow melted and turned into water, and I drank all the water. Now I'm better.",
            "It's just a cruel reminder that I'm single and likely to remain that way forever.",
            "Corrin, comfy, wow!",
            "You apologize to Brave Comfy Corn Duelist Reversed right this instant!",
            "Lord Xander kind of scares me. He always has this disgusted look on his face.",
            "Lady Camilla is so kind, but a bit too close for comfort sometimes. She's always patting me on the head!",
            "Lord Leo is as talented as he is intimidating. He does have a soft side once you get to know him.",
            "Lady Elise is a bundle of joy! If I weren't on duty so much I'd try to play with her more.",
            "Fire Emblem? Enga-gay?",
            "Sephiroth? From Final Fantasy?",
            "Yeehaw! Look at me I'm a cowboy Felicia.",
            "Fug",
            "Did you hear they're remaking Super Mario RPG?",
            "I've heard of this Edelgard person but we never spoke. Maybe I should axe her a few questions?",
            "We should watch Food Fight.",
            "Never forget the Care Bears Christmas Special on 2x speed.",
            "To this day I get confused on whether it's pronounced \"Revelation\" or \"Revelations\"",
            "They gave Jakob a spirit in Smash Bros. but not me! :(",
            "What color is my hair?",
            "Lilith isn't the only one that can turn into a fish, you know.",
            "I do like me some good cabbage.",
            "YOU THINK THIS IS A GAME!?",
            "Watch out, that doro do be flipping!",
            "Fire Emblem Fates was released in North America on February 19, 2016. Let that sink in.",
            "I'm still waiting for my invitation to the next Nintendo Direct.",
            "Did you know that in Japan, ice cream is often served with savory toppings like soy sauce or miso paste? Weird, right?",
            "I really do miss the Ice Tribe sometimes. After all, there snow place like home!",
            "I'm not the only one who thought Flora was recruitable in Chapter 8 of Conquest, right?",
            "They don't call me Felicia because of my personality or anything. It's just that my full name is Felicia the Catgirl, and that's too long to fit on my nametag.",
            "So is Revelation considered lost media now?",
        ];
    }
}
